language: go
go:
  - 1.14.x
os: linux
env:
  global:
    - GO111MODULE=on
  jobs:
    - TEST_DIR=movie-svc
    - TEST_DIR=user
    - TEST_DIR=tvshow
    - TEST_DIR=auth
script: cd $TEST_DIR && go test ./... -v
