version: '3.1'

services:
  # TV SHOW SERVICE
  xmedia-tvshows-svc:
    container_name: xmedia-tvshows-svc
    build: ./tvshow
    links:
      - xmedia-tvshow-db
    ports:
      - 8001:8001
    volumes:
      - /home/y0x/Videos:/data/tvshows

  # TV SHOW DATABASE
  xmedia-tvshow-db:
    container_name: xmedia-tvshows-db
    image: mongo:4.2.3
    ports:
      - 27017:27017

  # USER SERVICE
  xmedia-user-svc:
    container_name: xmedia-user-svc
    build: ./user
    links:
      - xmedia-user-db
    ports:
      - 8002:8002

  # USER DATABASE
  xmedia-user-db:
    container_name: xmedia-user-db
    image: mysql:8.0.20
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
        # - MYSQL_DATABASE=xmedia_users
    volumes:
      - ./user/init.sql:/docker-entrypoint-initdb.d/init.sql
