version: '3.1'

services:
  # TV SHOW SERVICE
  xmedia-tvshows-svc:
    container_name: xmedia-tvshows-svc
    build: ./tvshow
    links:
      - xmedia-tvshow-db
    labels:
      - traefik.http.routers.tvshowsvc.rule=Host("tvshowsvc")
    ports:
      - 8001:8001
    volumes:
      - /home/y0x/Videos:/data/tvshows

  # TV SHOW DATABASE
  xmedia-tvshow-db:
    container_name: xmedia-tvshows-db
    image: mongo:4.2.3
    labels:
      - traefik.enable=false
    ports:
      - 27017:27017

  # USER SERVICE
  xmedia-user-svc:
    container_name: xmedia-user-svc
    build: ./user
    links:
      - xmedia-user-db
    labels:
      - traefik.http.routers.usersvc.rule=Host("usersvc")
    ports:
      - 8002:8002

  # USER DATABASE
  xmedia-user-db:
    container_name: xmedia-user-db
    image: mysql:8.0.20
    labels:
      - traefik.enable=false
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=xmedia_users
    volumes:
      - ./user/init.sql:/docker-entrypoint-initdb.d/init.sql

  # TRAEFIK
  reverse-proxy:
    container_name: traefik
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
